version: '3.8'
services:
    # mpyc-node-1:
    #     build: .
    #     stdin_open: true
    #     tty: true
    #     command: ["python", "app/mpyc_script.py", "-P", "localhost", "-P", "172.23.0.3", "-P", "172.23.0.4", "-P", "172.23.0.5","-P", "172.23.0.6","-I 0"]
    #     # command: ["python", "app/mpyc_script.py", "-P", "localhost",  "-P", "172.23.0.5", "-P", "172.23.0.6", "-I 0"]
    #     networks:
    #         mpyc-net:
    #             ipv4_address: 172.23.0.2
    # mpyc-node2:
    #     build: .
    #     stdin_open: true
    #     tty: true
    #     command: ["python", "./app/mpyc_script.py", "-P", "172.23.0.2", "-P", "localhost", "-P", "172.23.0.4", "-P", "172.23.0.5","-P", "172.23.0.6","-I 1"]
    #     networks:
    #         mpyc-net:
    #             ipv4_address: 172.23.0.3
    # mpyc-node3:
    #     build: .
    #     stdin_open: true
    #     tty: true
    #     command: ["python", "./app/mpyc_script.py", "-P", "172.23.0.2", "-P", "172.23.0.3", "-P", "localhost", "-P", "172.23.0.5","-P", "172.23.0.6", "-I 2"]
    #     networks:
    #         mpyc-net:
    #             ipv4_address: 172.23.0.4
    # mpyc-node-malicious:
    #     build: .
    #     stdin_open: true
    #     tty: true
    #     command: ["python", "./app/malicious_sum.py", "-P", "172.23.0.2", "-P", "172.23.0.3", "-P", "172.23.0.4", "-P", "localhost","-P", "172.23.0.6", "-I 3"]
    #     # command: ["python", "./app/malicious_sum.py", "-P", "172.23.0.2", "-P", "localhost", "-P", "172.23.0.6", "-I 1"]
    #     networks:
    #         mpyc-net:
    #             ipv4_address: 172.23.0.5
    # mpyc-node-4:
    #     build: .
    #     stdin_open: true
    #     tty: true
    #     command: ["python", "./app/mpyc_script.py", "-P", "172.23.0.2", "-P", "172.23.0.3", "-P", "172.23.0.4", "-P", "172.23.0.5", "-P", "localhost", "-I 4"]
    #     # command: ["python", "./app/mpyc_script.py", "-P", "172.23.0.2", "-P", "172.23.0.5", "-P", "localhost", "-I 2"]
    #     networks:
    #         mpyc-net:
    #             ipv4_address: 172.23.0.6
    mpyc-node-1:
        build: .
        stdin_open: true
        tty: true
        command: ["python", "app/mpyc_script.py", "-P", "localhost", "-P", "172.23.0.3", "-I 0"]
        # command: ["python", "app/mpyc_script.py", "-P", "localhost",  "-P", "172.23.0.5", "-P", "172.23.0.6", "-I 0"]
        networks:
            mpyc-net:
                ipv4_address: 172.23.0.2
    mpyc-node2:
        build: .
        stdin_open: true
        tty: true
        command: ["python", "./app/mpyc_script.py", "-P", "172.23.0.2", "-P", "localhost","-I 1"]
        networks:
            mpyc-net:
                ipv4_address: 172.23.0.3
networks:
    mpyc-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.23.0.0/24