version: '3.8'

services:
  pycrypto-node1:
    build: .
    container_name: pycrypto-node1
    networks:
      pycrypto-net:
        ipv4_address: 172.27.0.2
    command: ["python", "app/script.py"]
    stdin_open: true
    tty: true

  # pycrypto-node2:
  #   build: .
  #   container_name: pycrypto-node2
  #   networks:
  #     pycrypto-net:
  #       ipv4_address: 172.27.0.3
  #   command: ["python", "app/nodo2.py"]
  #   stdin_open: true
  #   tty: true

  # Altri nodi...

networks:
  pycrypto-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/24
